import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useApp } from '../context/AppContext.jsx';

const games = [
  { id: 'aetheria', title: 'Chronicles of Aetheria', image: '/img/games/aetheria.jpg', genre: 'ARPG Fantasía Oscura', engine: 'Unreal Engine 5 (C++)', stage: 'Pre-Alpha', stars: '3,420', forks: '412', contributors: 18, roles: ['Gameplay Programmer (C++)', '3D Environment Artist', 'VFX Niagara Shaders'], tech: ['Unreal Engine 5', 'C++', 'Niagara VFX', 'Wwise'], summary: 'Action RPG cooperativo en tercera persona con combate souls-lite y calabozos procedurales.' },
  { id: 'neon', title: 'Neon Drifter: Override', image: '/img/games/neon-drifter.jpg', genre: 'Cyberpunk Roguelite', engine: 'Godot 4 (C# / GDScript)', stage: 'Alpha', stars: '5,890', forks: '730', contributors: 32, roles: ['Pixel Artist & Animador 2D', 'Level Designer Procedural', 'Sistemas de Audio FMOD'], tech: ['Godot 4', 'C#', 'GLSL Shaders', 'FMOD'], summary: 'Roguelite de acción frenética cyberpunk con hackeo táctico y tiempo bala.' },
  { id: 'voxel', title: 'VoxelForge: Worlds', image: '/img/games/voxelforge.jpg', genre: 'Sandbox & Engine Voxel', engine: 'Motor Propio (C++20 & Vulkan)', stage: 'Producción activa', stars: '8,120', forks: '1,105', contributors: 54, roles: ['Graphics Programmer (Vulkan)', 'Netcode Engineer', 'Physics Simulation Specialist'], tech: ['C++20', 'Rust', 'Vulkan API', 'GLSL'], summary: 'Motor voxel open source con destrucción total, fluidos y renderizado acelerado por GPU.' },
  { id: 'valhalla', title: 'Echoes of Valhalla', image: '/img/games/valhalla.jpg', genre: 'Aventura Nórdica', engine: 'Unity 6 (URP / C#)', stage: 'Beta', stars: '4,610', forks: '590', contributors: 26, roles: ['Narrative Writer', 'Unity Shader Specialist', 'Sonidista Foley'], tech: ['Unity 6', 'C#', 'Shader Graph', 'Wwise'], summary: 'Aventura de navegación nórdica, supervivencia oceánica y mitología viva.' }
];

export default function Landing() {
  const { user } = useApp();
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState('');
  const [favorites, setFavorites] = useState([]);
  const destination = user ? '/dashboard' : '/register';
  const visibleGames = useMemo(() => games.filter(game => {
    const term = query.trim().toLowerCase();
    const matchesFilter = filter === 'all' || (filter === 'rpg' && game.genre.toLowerCase().includes('rpg')) || (filter === 'rogue' && game.genre.toLowerCase().includes('rogue')) || (filter === 'engine' && game.id === 'voxel');
    return matchesFilter && (!term || [game.title, game.genre, game.engine, game.summary, ...game.roles, ...game.tech].join(' ').toLowerCase().includes(term));
  }), [filter, query]);
  const toggleFavorite = id => setFavorites(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);

  return <div className="studio-home">
    <header className="studio-nav"><a href="#inicio" className="studio-brand"><span className="studio-brand-icon">🎮</span><span>ENTYTEC<span>OLLAB</span></span></a><nav><a href="#explorar">Explorar Videojuegos</a><a href="#caracteristicas">Cómo colaborar</a><a href="#comunidad">Comunidad EntyTec</a><a href="https://github.com" target="_blank" rel="noreferrer">⌘ GitHub ↗</a></nav><div className="studio-nav-actions">{user ? <><Link to="/perfil">{user.name}</Link><Link className="studio-primary small" to="/dashboard">Ir al panel</Link></> : <><Link to="/login">Iniciar sesión</Link><Link className="studio-primary small" to="/register">Crear cuenta</Link></>}</div></header>
    <main>
      <section className="studio-hero" id="inicio"><div className="studio-glow" /><div className="studio-container studio-center"><span className="studio-pill"><i /> ESTUDIO OFICIAL DE DESARROLLO DE VIDEOJUEGOS</span><h1>Desarrollo Colaborativo de <span>Videojuegos en EntyTec</span></h1><p>La plataforma oficial de EntyTec para organizar proyectos de videojuegos y reunir a programadores, artistas 3D, diseñadores y compositores apasionados por el desarrollo de juegos.</p><div className="studio-actions"><Link className="studio-primary" to={destination}>Crear Cuenta Gratis <b>→</b></Link>{!user && <Link className="studio-secondary" to="/login">Iniciar Sesión</Link>}</div><div className="studio-metrics"><span><b>14,200+</b> Devs activos</span><i>/</i><span><b>1,850+</b> Repositorios</span><i>/</i><span><b>100%</b> Open Source & Libre</span></div><div className="studio-benefits"><article><b>♟</b><div><strong>Equipos Multidisciplinarios</strong><small>Programación + Arte + Audio</small></div></article><article><b>⌘</b><div><strong>Git LFS & Repos Sincronizados</strong><small>Soporte nativo para assets 3D</small></div></article><article><b>✦</b><div><strong>Publicación en Steam</strong><small>Créditos oficiales en el juego</small></div></article></div></div></section>
      <section className="studio-showcase" id="explorar"><div className="studio-container"><div className="studio-section-head"><div><span className="studio-pill muted">🎮 PROYECTOS OFICIALES DE ENTYTEC</span><h2>Descubre en qué videojuegos estamos trabajando</h2><p>Explora libremente los detalles, el motor y las tareas de cada videojuego, aunque no tengas una cuenta.</p></div><Link className="studio-primary" to={destination}>Crear cuenta de desarrollador ↗</Link></div><div className="studio-tools"><div className="studio-filter-tabs">{[['all', 'Todos los videojuegos'], ['rpg', 'Action RPG'], ['rogue', 'Roguelite & Arcade'], ['engine', 'Motores & Voxel']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="studio-search"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por rol, motor o título..." /></label></div><div className="studio-games">{visibleGames.map(game => <article className="studio-game" key={game.id}><div className="studio-game-art"><img src={game.image} alt={game.title} /><div className="studio-art-shade" /><div className="studio-game-badges"><span>{game.genre}</span><span>{game.engine}</span></div><div className="studio-game-stage"><span>{game.stage}</span><button onClick={() => toggleFavorite(game.id)} aria-label={`Guardar ${game.title}`}>{favorites.includes(game.id) ? '★' : '☆'}</button></div></div><div className="studio-game-copy"><div className="studio-game-title"><h3>{game.title}</h3><span>MIT / Open Assets</span></div><p>{game.summary}</p><div className="studio-roles"><b>Roles buscando colaboradores:</b><div>{game.roles.map(role => <span key={role}>{role}</span>)}</div></div><div className="studio-tech">{game.tech.map(tech => <span key={tech}>#{tech}</span>)}</div><div className="studio-game-bottom"><div><span>★ {game.stars}</span><span>⌘ {game.forks}</span><span>♟ {game.contributors} devs</span></div><div><Link className="studio-view" to={destination}>Ver proyecto</Link><Link className="studio-apply" to={destination}>Postularme</Link></div></div></div></article>)}</div>{visibleGames.length === 0 && <div className="studio-empty"><p>No se encontraron videojuegos con ese criterio.</p><button onClick={() => { setFilter('all'); setQuery(''); }}>Restablecer filtros</button></div>}</div></section>
      <section className="studio-flow" id="caracteristicas"><div className="studio-container"><span className="studio-pill muted">✦ ORGANIZACIÓN GAMEDEV EN ENTYTEC</span><h2>Un flujo estructurado para crear videojuegos en equipo</h2><p>Organiza cada videojuego con documentos de diseño claros, tareas por motor y soporte para todo el equipo creativo.</p><div className="studio-steps"><article><b>▣</b><small>PASO 01</small><h3>Explora y conoce el proyecto</h3><p>Revisa la historia del juego, el motor utilizado, las mecánicas y los roles abiertos.</p></article><article><b>♟</b><small>PASO 02</small><h3>Postulación ágil y tareas</h3><p>Elige el rol que encaja con tus fortalezas y toma tareas con guías claras.</p></article><article><b>✦</b><small>PASO 03</small><h3>Lanzamiento en Steam & créditos</h3><p>Tus contribuciones aprobadas te acreditan oficialmente en cada producción.</p></article></div><div className="studio-community" id="comunidad"><div><span>COMUNIDAD GAMEDEV ENTYTEC</span><h3>¿Quieres dar vida a mecánicas o crear arte para un videojuego real?</h3><p>Únete a las producciones activas de EntyTec Studios y colabora con otros creadores.</p></div><Link className="studio-primary" to={destination}>Unirme a EntyTec Studios →</Link></div></div></section>
    </main>
    <footer className="studio-footer"><div className="studio-container"><div><a href="#inicio" className="studio-brand"><span className="studio-brand-icon">⌘</span><span>ENTY<span>COLLAB</span></span></a><p>Plataforma oficial de desarrollo y organización de EntyTec Video Game Studios.</p></div><div><b>Ecosistema</b><a href="#explorar">Explorar repos</a><a href="#caracteristicas">Cómo funciona</a><a href="#comunidad">Comunidad</a></div><div><b>Estado de la red</b><span>● Hub Central: Operacional</span><span>GitHub Sync: 100% online</span></div></div><p className="studio-copyright">© {new Date().getFullYear()} ENTYTECOLLAB. Desarrollado con tecnología libre.</p></footer>
  </div>;
}
